--YILLARA GORE ISE ALINAN KADIN VE ERKEK CALISAN SAYILARINI BELIRT

select distinct YEAR(p.INDATE) as year,
(select COUNT(*) from HR.dbo.PERSONN where GENDER = 'K' and YEAR(INDATE)=YEAR(p.INDATE)) AS FEMALE_COUNT,
(select COUNT(*) from HR.dbo.PERSONN where GENDER = 'E' and YEAR(INDATE)=YEAR(p.INDATE)) AS MALE_COUNT
from HR.dbo.PERSONN as p
ORDER BY 1 
